language: python 
python:
  - '2.7'
  - '3.5' 
install:
- pip install -r requirements.txt 
script: python test_example.py 
deploy:
  provider: pypi
  user: goodspeed     # pypi 用户名
  password: password  # pypi 密码   
  on:     
    python: 2.7     
    tags: true     
    branch: master
