language: python 
python:
  - '2.7'
  - '3.5' 
install: true
# - pip install -r requirements.txt 
script: python Physics.py 
deploy:
  provider: pypi
  user: Mryan     # pypi 用户名
  password: ${password}  # pypi 密码
  skip_cleanup: true   
  on:     
    python: 2.7     
    tags: true     
